using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WallHitCollision : MonoBehaviour
{
    private bool isHit = false;   // •Ç‚ÉG‚ê‚Ä‚¢‚é‚©‚Ì”»’è

    private bool IsHitWall(Collider _other)   // •Ç‚ÉG‚ê‚½‚©”»’è
    {
        return _other.gameObject.CompareTag("Wall");
    }

    private void OnTriggerStay(Collider other)
    {
        // •Ç‚ÉG‚ê‚½‚çæ‚Ìˆ—‚Ö
        if (!IsHitWall(other)) return;

        isHit = true;
    }

    private void OnTriggerExit(Collider other)
    {
        // •Ç‚É—£‚ê‚½‚çæ‚Ìˆ—‚Ö
        if (!IsHitWall(other)) return;

        isHit = false;
    }

    public bool IsHit
    {
        get { return isHit; }
    }
}
